      - name: Build target 3105
        run: |
          mkdir -p output

          xcodebuild \
            -project ThreeOneOSFive.xcodeproj \
            -target 3105 \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CONFIGURATION_BUILD_DIR="$PWD/output" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build
                  - name: Package IPA
        run: |
          rm -rf Payload
          mkdir Payload
          cp -R output/3105.app Payload/3105.app
          zip -qry 3105-2.0-ios16-unsigned.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: 3105-2.0-ios16-unsigned
          path: 3105-2.0-ios16-unsigned.ipa
